---
- name: Copy Configuration File
  become: yes
  template:
    src: enterprise-search.yml.j2
    dest: "{{ es_conf_dir }}/enterprise-search.yml"
    owner: "{{ es_group }}"
    group: "{{ es_group }}"
    mode: "660"
    force: yes
  register: system_change
  notify:
      - reload systemd configuration
      - restart enterprise-search

- name: Copy Environemnt Variables File
  become: yes
  template:
    src: env.sh
    dest: "{{ es_conf_dir }}/env.sh"
    owner: "{{ es_group }}"
    group: "{{ es_group }}"
    mode: "660"
    force: yes
  register: system_change
  notify:
      - reload systemd configuration
      - restart enterprise-search

